# Generated by Django 5.2.1 on 2025-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcertificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcertificate',
            name='collected_date',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='printed_date',
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='collected_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Collected By (Student/Parent Name)'),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='collection_remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='status',
            field=models.CharField(choices=[('issued', 'Certificate Issued & Given'), ('pending_collection', 'Pending Collection'), ('revoked', 'Revoked')], default='issued', max_length=20),
        ),
    ]
