# Generated by Django 5.2.1 on 2025-12-06 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcertificate', '0002_remove_studentcertificate_collected_date_and_more'),
        ('xcoursefee', '0002_kit_coursekit_kitfee'),
        ('xstudent', '0006_attendance_attendancesummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='certificateverification',
            name='certificate',
        ),
        migrations.AlterModelOptions(
            name='studentcertificate',
            options={'ordering': ['-issue_date', '-created_at'], 'verbose_name': 'Certificate Issue Record', 'verbose_name_plural': 'Certificate Issue Records'},
        ),
        migrations.AlterUniqueTogether(
            name='studentcertificate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Certificate Number'),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='xcoursefee.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='issue_date',
            field=models.DateField(verbose_name='Issue Date (Date Given to Student)'),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Issued By'),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks (Optional)'),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='xstudent.newstudent', verbose_name='Student'),
        ),
        migrations.DeleteModel(
            name='CertificateBatch',
        ),
        migrations.DeleteModel(
            name='CertificateVerification',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='certificate_pdf',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='collection_remarks',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='custom_text',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='last_verified',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='revocation_reason',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='revoked_by',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='revoked_date',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='signatories',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='template',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='studentcertificate',
            name='verification_count',
        ),
        migrations.DeleteModel(
            name='CertificateSignatory',
        ),
        migrations.DeleteModel(
            name='CertificateTemplate',
        ),
    ]
