# Generated by Django 5.2.1 on 2025-12-06 07:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmark', '0001_initial'),
        ('xstudent', '0006_attendance_attendancesummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentMark',
            new_name='Mark',
        ),
    ]
