# Generated by Django 5.2.1 on 2025-06-03 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xstudent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='bus_route',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='class_section',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='doctor_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='extracurricular_activities',
            field=models.TextField(blank=True, help_text='Interests and activities'),
        ),
        migrations.AddField(
            model_name='student',
            name='family_income',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_structure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any medical conditions, allergies, or special requirements'),
        ),
        migrations.AddField(
            model_name='student',
            name='medications',
            field=models.TextField(blank=True, help_text='Current medications'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Kuwaiti', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Judaism', 'Judaism'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or notes'),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs',
            field=models.TextField(blank=True, help_text='Any special educational needs or accommodations'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Scholarship', 'Scholarship'), ('International', 'International'), ('Transfer', 'Transfer'), ('Special Needs', 'Special Needs')], default='Regular', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('Own Transport', 'Own Transport'), ('School Bus', 'School Bus'), ('Public Transport', 'Public Transport'), ('Walking', 'Walking')], max_length=20),
        ),
    ]
