# Generated by Django 5.2.1 on 2025-06-03 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xstudent', '0002_student_admission_date_student_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('grade', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email_id', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('student_profile_picture', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_company_name', models.CharField(blank=True, max_length=200)),
                ('father_mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('father_email_id', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_company_name', models.CharField(blank=True, max_length=200)),
                ('mother_mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('mother_email_id', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('guardian_mobile_no', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('sibling_1_name', models.CharField(blank=True, max_length=100)),
                ('sibling_1_age', models.PositiveIntegerField(blank=True, null=True)),
                ('sibling_2_name', models.CharField(blank=True, max_length=100)),
                ('sibling_2_age', models.PositiveIntegerField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state_emirates_province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('select_mobile_number', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother')], max_length=10)),
                ('mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
