# Generated by Django 5.2.1 on 2025-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xstudent', '0003_newstudent_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='active', max_length=10),
        ),
    ]
