# Generated by Django 5.2.1 on 2025-06-06 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xstudent', '0004_newstudent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Full name of the old student', max_length=100, verbose_name='Student Name')),
                ('date_of_birth', models.DateField(help_text="Student's date of birth", verbose_name='Date of Birth')),
                ('student_code', models.CharField(help_text='Unique identifier for the student', max_length=20, unique=True, verbose_name='Student Code')),
                ('email', models.EmailField(help_text="Student's email address", max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('mobile_number', models.CharField(help_text="Student's mobile number", max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Number')),
                ('tenth_level_completed_date', models.DateField(help_text='Date when student completed 10th level', verbose_name='10th Level Completed Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Old Student',
                'verbose_name_plural': 'Old Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
