# Generated by Django 5.2.1 on 2025-06-18 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xstudent', '0005_oldstudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of attendance record', verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10, verbose_name='Attendance Status')),
                ('time_in', models.TimeField(blank=True, help_text='Time when student arrived', null=True, verbose_name='Time In')),
                ('time_out', models.TimeField(blank=True, help_text='Time when student left', null=True, verbose_name='Time Out')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='xstudent.newstudent', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(help_text='Month (1-12)', verbose_name='Month')),
                ('year', models.PositiveIntegerField(help_text='Year', verbose_name='Year')),
                ('total_days', models.PositiveIntegerField(default=0, help_text='Total working days in the month', verbose_name='Total Days')),
                ('present_days', models.PositiveIntegerField(default=0, verbose_name='Present Days')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='Absent Days')),
                ('late_days', models.PositiveIntegerField(default=0, verbose_name='Late Days')),
                ('excused_days', models.PositiveIntegerField(default=0, verbose_name='Excused Days')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Attendance Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='xstudent.newstudent', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'ordering': ['-year', '-month'],
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
