# Generated by Django 5.2.1 on 2025-06-19 10:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcoursefee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kit Name')),
                ('description', models.TextField(verbose_name='Kit Description')),
                ('kit_code', models.CharField(max_length=20, unique=True, verbose_name='Kit Code')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Kit Price (KWD)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stock Quantity')),
                ('minimum_stock', models.PositiveIntegerField(default=10, verbose_name='Minimum Stock Level')),
                ('contents', models.TextField(blank=True, verbose_name='Kit Contents')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Supplier')),
                ('supplier_contact', models.CharField(blank=True, max_length=100, verbose_name='Supplier Contact')),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='available', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Mandatory Kit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required Kit')),
                ('distribution_date', models.DateField(blank=True, null=True, verbose_name='Distribution Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_kits', to='xcoursefee.course', verbose_name='Course')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_kits', to='xcoursefee.kit', verbose_name='Kit')),
            ],
            options={
                'verbose_name': 'Course Kit',
                'verbose_name_plural': 'Course Kits',
                'ordering': ['course', 'kit'],
                'unique_together': {('course', 'kit')},
            },
        ),
        migrations.CreateModel(
            name='KitFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Kit Fee Amount (KWD)')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cheque', 'Cheque'), ('online', 'Online Payment')], max_length=20, verbose_name='Payment Method')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Payment Reference')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('collected', 'Collected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('collected_by', models.CharField(blank=True, max_length=100, verbose_name='Collected By')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_fees', to='xcoursefee.coursekit', verbose_name='Course Kit')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_fees', to='xcoursefee.studentenrollment', verbose_name='Enrollment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Kit Fee',
                'verbose_name_plural': 'Kit Fees',
                'ordering': ['-created_at'],
                'unique_together': {('enrollment', 'course_kit')},
            },
        ),
    ]
