# Generated by Django 5.2.1 on 2025-12-06 18:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xstudent', '0006_attendance_attendancesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Fee Amount (KWD)')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fees', to='xstudent.newstudent')),
            ],
            options={
                'verbose_name': 'Transport Fee',
                'verbose_name_plural': 'Transport Fees',
                'ordering': ['-payment_date'],
            },
        ),
    ]
